### ISSUE TITLE
Pressing Ctrl on the editor also triggers the suggestion panel

### ISSUE THREAD

**Issue by louisgv** [isis97/atom-terminal-panel#32] opened 2015-05-16 19:06 UTC
Seems like this behavior need some constraint. Currently Ctrl anywhere bring up the suggestion panel.

**Comment by batjko** [comment] 2015-08-06 14:34
Technically, #37 is a duplicate of this one, but all the discussion and more details are on there. I'd therefore close this one off.

**Closed** 2015-08-13 15:20 UTC
Labels: bug
